version: '3.8'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: ./user-service
    container_name: app
    volumes:
      - images:/home/images
      - users:/home/users
      - tokens:/home/tokens
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=pisti333
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - UPLOAD_DIRECTORY=/home/images
      - DBPW=pisti333
      - MAILPW=evcyflwepibrspny
      - IPV4=192.168.0.15
      - MAX_SIZE=10MB

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=compose-postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pisti333

volumes:
  images:
  users:
  tokens: