spring:
  application:
    name: user-service
  config:
    import: "configserver:http://localhost:8088/"

  datasource:
    url: jdbc:postgresql://localhost:5432/harmonicrainbow_users
    username: postgres
    password: ${DBPW}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: harmonicrainbow7
    password: ${MAILPW}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  #  properties:
#    hibernate:
#      format_sql=true
  #jpa.show-sql=true
