spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/harmonicrainbow
    username: postgres
    password: ${DBPW}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: harmonicrainbow7
    password: ${MAILPW}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: ${MAX_SIZE}
      max-request-size: ${MAX_SIZE}
#  security:
#    user:
#      name: pisti
#      password: pisti333
