spring:
  application:
    name: image-service
  config:
    import: "configserver:http://localhost:8088"

  datasource:
    url: jdbc:postgresql://localhost:5432/harmonicrainbow_images
    username: postgres
    password: ${DBPW}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 10MB
