spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/harmonicrainbow
    username: postgres
    password: ${DBPW}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: harmonicrainbow7
    password: ${MAILPW}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
