version: '3.8'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    volumes:
      - images:/home/images
      - users:/home/users
      - tokens:/home/tokens
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - "5432:5432"
    env_file:
      - .env

volumes:
  images:
  users:
  tokens:
